---
output: 
  bookdown::pdf_document2:
    toc: False
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lastpage}
- \usepackage{amsmath}
- \usepackage{tocloft}
bibliography: ref.bib
link-citations: yes
always_allow_html: yes
---


\fancyfoot[C]{\thepage\ of \pageref{LastPage}}


\newpage
\pagestyle{fancy}
\fancyhead[L]{\slshape Land Use Cover}
\fancyhead[C]{\slshape STAT 6500}
\fancyhead[R]{\slshape Project Proposal}

# Problem statement

Based on the study from @urbanlandcover, urban land-cover information is essential for numerous urban-planning applications, for instance, green space analysis (@inbook) and urban land-use mapping (@article). Most land cover has traditionally been obtained from satellite images using pixel-based image classification techniques. Nevertheless, in fine spatial resolution images with spectral variability within the same class can lead to low accuracy for classification using pixel-based image classification techniques. Therefore, @urbanlandcover presented the Object-based classification methods involving segmentation of the image on different scales. The average size of the segment will vary depending on the specified scale parameter. These scales were ranging from 40 to 140 with 20 intervals in this study. For each image segment, features such as spectral (mean values and variance for each band), mean normalized differential vegetation index (NDVI), area, shape, texture, length and so on were calculated in one of different scales (21 features for each scale). Target type for classification includes tree, grass, buildings, concrete, asphalt, vehicles, pools, soil and shadow.  

This project aims to use the machine learning techniques and statistical tools which are different than the techniques used from the study of @urbanlandcover to predict the target class of the object derived from segmentation at different scales of high-resolution urban-land cover image. Three machine learning techniques which are neural networks, random forest and k-nearest neighbors will be used for this project. The comparison of different classifier for each scale and how well the classifier can perform at each scale will be analyzed. In total, 21 machine learning models will be implemented in this study (seven scales with three machine learning techniques for each scale) 



# References

